---
- name: Manage JetBrains and VSCode packages via COPR repositories
  hosts: all
  become: yes

  vars:

    vscode_binary_url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
    vscode_binary_filename: "vscode-linux-x64-stable.tar.gz"
    vscode_install_dir: "/usr/local/vscode"

  tasks:
    - name: Enable JetBrains COPR repository
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Download VSCode binary
      ansible.builtin.get_url:
        url: "{{ vscode_binary_url }}"
        dest: "/tmp/{{ vscode_binary_filename }}"
        mode: '0644'

    - name: Create VSCode installation directory
      ansible.builtin.file:
        path: "{{ vscode_install_dir }}"
        state: directory
        mode: '0755'

    - name: Extract VSCode binary
      ansible.builtin.unarchive:
        src: "/tmp/{{ vscode_binary_filename }}"
        dest: "{{ vscode_install_dir }}"
        remote_src: yes
        creates: "{{ vscode_install_dir }}/bin/code"

    - name: Create symbolic link for VSCode binary
      ansible.builtin.file:
        src: "{{ vscode_install_dir }}/VSCode-linux-x64/bin/code"
        dest: "/usr/local/bin/code"
        state: link
