---

- name: Install Fedora Core Packages
  hosts: all
  become: yes
  tasks:
    - name: Install mediacodecs
      command: sudo dnf install gstreamer1-plugin-openh264 gstreamer1-plugin-libav --exclude=gstreamer1-plugins-bad-free-devel lame\* --exclude=lame-devel ffmpeg-free -y


