---
- name: Set GNOME settings for buttons and dark mode
  hosts: localhost
  tasks:
    - name: Set button layout to 'close,minimize'
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.wm.preferences button-layout ':close'"

    - name: Set GTK theme to dark
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'"

    - name: Set GTK theme to dark
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.interface enable-animations false"

    - name: Set desktop movements // doesnt work??
      ansible.builtin.shell: |
        for i in {1..9}; do gsettings set "org.gnome.desktop.wm.keybindings" "switch-to-workspace-$i" "['<Super>$i']" ; done
        for i in {1..9}; do gsettings set "org.gnome.desktop.wm.keybindings" "move-to-workspace-$i" "['<Super><Shift>$i']" ; done