version: "3"

services:
  server:
    image: gitea/gitea:1.22
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - SSH_LISTEN_PORT=22
      - SSH_PORT=222
      - GITEA__admin__USER=admin  # Admin username
      - GITEA__admin__PASSWORD=admin123  # Admin password
      - GITEA__admin__EMAIL=admin@example.com  # Admin email
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
        # first run without ini
      - ./conf/app.ini:/data/gitea/conf/app.ini 
      - ./icon.svg:/data/gitea/public/assets/img/logo.svg
      - ./icon.svg:/data/gitea/public/assets/img/favicon.svg
      - ./templates:/data/gitea/templates
    ports:
      - "80:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql
