version: "3.7"

services:
    reverse-proxy:
        #image: docker.io/library/caddy:alpine
        build: .
        container_name: caddy
        network_mode: host
        command: caddy run --config /etc/caddy/Caddyfile
        #command: caddy reverse-proxy --from :80 --to http://localhost:8001
        restart: always
        volumes:
          - ./CaddyfileCorgiWiki:/etc/caddy/Caddyfile:z
          - ./static:/static:z
          - ./list/index.html:/list/index.html:z
          - ./caddy_data:/data:z

    anubis-nginx:
        image: ghcr.io/techarohq/anubis:latest
        environment:
          BIND: ":8080"
          DIFFICULTY: "4"
          METRICS_BIND: ":9090"
          SERVE_ROBOTS_TXT: "true"
          TARGET: "http://localhost:8001"
          POLICY_FNAME: "/data/cfg/botPolicy.yaml"
          OG_PASSTHROUGH: "true"
          OG_EXPIRY_TIME: "24h"
        network_mode: host
        volumes:
          - "./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
          - "./happy.webp:/data/happy.webp:ro"
