version: "3.7"

services:
    reverse-proxy:
        image: docker.io/library/caddy:alpine
        container_name: caddy
        network_mode: host
        command: caddy run --config /etc/caddy/Caddyfile
        #command: caddy reverse-proxy --from :80 --to http://localhost:8001
        restart: always
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
          - ./static:/static
          - ./list/index.html:/list/index.html
          - ./caddy_data:/data
