version: "3.7"

services:
    reverse-proxy:
        image: hainz98/caddy
        #build: .
        container_name: caddy
        network_mode: host
        command: caddy run --config /etc/caddy/Caddyfile
        #command: caddy reverse-proxy --from :80 --to http://localhost:8001
        restart: always
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile:z
          - ./caddy_data:/data:z
