---
- name: Manage JetBrains and VSCode packages via COPR repositories
  hosts: all
  become: yes

  vars:
    jetbrains_repo_name: "jetbrains_copr"
    jetbrains_repo_description: "JetBrains COPR repository"
    jetbrains_repo_baseurl: "https://copr-be.cloud.fedoraproject.org/results/medzik/jetbrains/fedora-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/"

    vscode_repo_name: "vscode_copr"
    vscode_repo_description: "VSCode COPR repository"
    vscode_repo_baseurl: "https://copr-be.cloud.fedoraproject.org/results/topazus/vscode/fedora-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/"

    jetbrains_packages:
      - clion
      - pycharm-professional
      - intellij-idea-ultimate
    vscode_packages:
      - vscode

  tasks:
    - name: Enable JetBrains COPR repository
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add JetBrains COPR repository
      ansible.builtin.yum_repository:
        name: "{{ jetbrains_repo_name }}"
        description: "{{ jetbrains_repo_description }}"
        baseurl: "{{ jetbrains_repo_baseurl }}"
        gpgcheck: no
        enabled: yes

    - name: Install JetBrains packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ jetbrains_packages }}"

    - name: Add VSCode COPR repository
      ansible.builtin.yum_repository:
        name: "{{ vscode_repo_name }}"
        description: "{{ vscode_repo_description }}"
        baseurl: "{{ vscode_repo_baseurl }}"
        gpgcheck: no
        enabled: yes

    - name: Install VSCode
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ vscode_packages }}"
