---
- name: Install Packages
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose
        - podman
        - neovim
        - trash-cli
        - openssl-devel
        - nodejs
        - npm 
        - distrobox
        - thefuck

    - name: Ensure Docker service is enabled and started
      service:
        name: docker
        state: started
        enabled: yes
