---
- name: Install Homecomputer Packages
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - timeshift
        - fish
        - trash-cli

