#/etc/borgmatic/config.yaml
location:
  source_directories:
    - "/media/maine/hdd1"
    - "/var/lib/rancher/k3s/storage"
    - "/home/maine/infra"
  repositories:
    - "/media/maine/HDD2/borg-repo"
    - "ssh://root@corgijan.dev/root/backups-maine/borg-repo"

storage:
  encryption_passphrase: "cassini"
  compression: zstd,9

retention:
  keep_daily: 7
  keep_weekly: 2
  keep_monthly: 5
  keep_yearly: 6
