version: '3.3'

services:
  cache:
    container_name: cache_registry
    restart: always
    image: registry
    environment:
      REGISTRY_AUTH: 'htpasswd'
      REGISTRY_AUTH_HTPASSWD_REALM: 'basic-realm'
      REGISTRY_AUTH_HTPASSWD_PATH: '/httpasswd_storage/htpasswd'
    ports:
      - 127.0.0.1:20001:5000
    volumes:
      - ./config/config_cache.yml:/etc/docker/registry/config.yml:z
      - ./data:/var/lib/registry:z
      - ./htpasswd:/httpasswd_storage/htpasswd:z
  #environment:
    #- "STANDALONE=true"
    #- "MIRROR_SOURCE=https://registry-1.docker.io"
    #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
      #
  registry:
    container_name: registry
    restart: always
    image: registry
    environment:
      REGISTRY_AUTH: 'htpasswd'
      REGISTRY_AUTH_HTPASSWD_REALM: 'basic-realm'
      REGISTRY_AUTH_HTPASSWD_PATH: '/httpasswd_storage/htpasswd'
    ports:
      - 127.0.0.1:20002:5000
    volumes:
      - ./config/config_registry.yml:/etc/docker/registry/config.yml:z
      - ./data:/var/lib/registry:z
      - ./htpasswd:/httpasswd_storage/htpasswd:z
  #environment:
    #- "STANDALONE=true"
    #- "MIRROR_SOURCE=https://registry-1.docker.io"
    #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
