version: "3.7"

services:
    caddy-ingress:
        #image: docker.io/library/caddy:alpine
        build: .
        network_mode: host
        command: caddy run --config /etc/caddy/Caddyfile
        #command: caddy reverse-proxy --from :80 --to http://localhost:8001
        restart: always
        volumes:
          - ./ingress.Caddyfile:/etc/caddy/Caddyfile:z
          - ./caddy_data:/data:z
          - ./happy.webp:/srv/happy.webp:ro
