version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
    entrypoint: >
      /bin/sh -c "
      printf '
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: \"node\"
          static_configs:
            - targets: [\"node_exporter_proxy:80\"]
      ' > /etc/prometheus/prometheus.yml &&
      exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml
      "

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:9101'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    expose:
      - "9101"   # only expose internally

  node_exporter_proxy:
    image: nginx:alpine
    container_name: node_exporter_proxy
    depends_on:
      - node_exporter
    ports:
      - "9100:80"
    restart: unless-stopped
    command: >
      /bin/sh -c "
      apk add --no-cache apache2-utils &&
      htpasswd -bBc /etc/nginx/.htpasswd exporter secret &&
      printf '
      events {}
      http {
        server {
          listen 80;
          location / {
            proxy_pass http://node_exporter:9101;
            auth_basic \"Restricted\";
            auth_basic_user_file /etc/nginx/.htpasswd;
          }
        }
      }' > /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'
      "

volumes:
  prometheus_data:
