global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
    basic_auth:
      username: poppy
      password: PoppyRoot012

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    basic_auth:
      username: poppy
      password: PoppyRoot012
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    basic_auth:
      username: poppy
      password: PoppyRoot012
